version: '3'

services:

  dbmysql:
    build: ./docker-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pa55word

  fishingserver:
    image: symb1os/fishingserver:latest
    restart: always
    ports:
      - "8080:8080"
    links:
      - dbmysql:dbmysql
    volumes:
      - ./fishing-resources:/usr/local/fishing-resources

  monitoring:
    image: symb1os/monitoring:latest
    restart: always
    ports: 
      - "8081:8080"
    links:
      - dbmysql:dbmysql
    volumes:
      - ./fishing-resources:/usr/local/fishing-resources
